import { execFile } from 'node:child_process';
import * as os from 'node:os';
import { mkdtempSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, test, vi, beforeEach, afterEach } from 'vitest';
import { runHermesAgentGeneration } from '../server/services/hermes-agent';
import type { AnalyzeContractResult, PageConfig } from '../shared/schema';

vi.mock('node:child_process', () => ({
  execFile: vi.fn(),
}));

const mockedExecFile = vi.mocked(execFile);
const originalCwd = process.cwd();

const analysis: AnalyzeContractResult = {
  contractAddress: '0x1234567890123456789012345678901234567890',
  contractName: 'MockToken',
  chain: 'conflux-espace-testnet',
  requestedSkill: 'token-dashboard',
  contractType: 'token',
  skillMatch: true,
  recommendedSkills: ['token-dashboard'],
  methods: [],
  dangerousMethods: [],
  warnings: ['Connect wallet before writing.'],
};

const deterministicPageConfig: PageConfig = {
  chainId: 71,
  rpcUrl: 'https://evmtestnet.confluxrpc.com',
  contractAddress: analysis.contractAddress,
  skill: 'token-dashboard',
  title: 'Token dashboard',
  description: 'Deterministic page',
  chain: 'conflux-espace-testnet',
  contractName: 'MockToken',
  warnings: ['Connect wallet before writing.'],
  dangerousMethods: [],
  methods: [],
  sections: [],
};

beforeEach(() => {
  mockedExecFile.mockReset();
  delete process.env.HERMES_AGENT_COMMAND;
});

afterEach(() => {
  process.chdir(originalCwd);
});

describe('runHermesAgentGeneration', () => {
  test('calls hermes-agent with sanitized task context and parses generated page output', async () => {
    mockedExecFile.mockImplementation((_file, _args, _options, callback) => {
      callback?.(
        null,
        JSON.stringify({
          summary: 'Hermes generated a sharper token app.',
          contractAnalysis: {
            contractType: 'token',
            recommendedSkill: 'token-dashboard',
            readMethods: [],
            writeMethods: [],
            dangerousMethods: [],
            warnings: ['Connect wallet before writing.'],
          },
          pageConfig: {
            ...deterministicPageConfig,
            title: 'Hermes Token Console',
            description: 'Generated by hermes-agent',
          },
          status: 'success',
          error: '',
        }),
        '',
      );
      return {} as ReturnType<typeof execFile>;
    });

    process.chdir(mkdtempSync(join(os.tmpdir(), 'dapp-builder-hermes-agent-')));

    const result = await runHermesAgentGeneration({
      input: {
        contractAddress: analysis.contractAddress,
        chain: 'conflux-espace-testnet',
        skill: 'token-dashboard',
        model: 'gpt-5.4',
        apiKey: 'secret-api-key',
      },
      abi: [],
      analysis,
      deterministicPageConfig,
    });

    expect(result?.pageConfig.title).toBe('Hermes Token Console');
    expect(result?.pageConfig.description).toBe('Generated by hermes-agent');
    expect(mockedExecFile).toHaveBeenCalledWith(
      'hermes-agent',
      [expect.stringContaining(analysis.contractAddress)],
      expect.objectContaining({ timeout: expect.any(Number) }),
      expect.any(Function),
    );
    const prompt = mockedExecFile.mock.calls[0]?.[1]?.[0] as string;
    expect(prompt).toContain('token-dashboard');
    expect(prompt).not.toContain('secret-api-key');
    expect(prompt).toContain('不是 scan');
    expect(prompt).toContain('Revoke approval');
    expect(prompt).toContain('更像产品');
    expect(prompt).toContain('"primaryActions": []');
  });
});
